In [1]:
import numpy as np

### 首先将我们的数据初始

In [2]:
X = np.array([[1,1,1],
              [0,1,1],
              [0,0,1]])
import numpy as np

y = np.array([[6],
              [5],
              [3]])

print(X.shape)
print(y.shape)

(3, 3)
(3, 1)


In [3]:
w = np.zeros((3, 1))
print(w)

[[ 0.]
 [ 0.]
 [ 0.]]


然后我们计算 h = X * w 的值,在这里矩阵相乘的话用np.dot()函数

In [4]:
h = X.dot(w)

In [5]:
deff = h - y

In [6]:
loss = deff.T.dot(deff)

In [7]:
loss

array([[ 70.]])

In [8]:
ddeff = 2 * deff

In [9]:
dh = 1 * ddeff

In [10]:
dw = X.T.dot(dh)

In [11]:
lr = 0.01
for i in range(1000):
    #前向
    h = X.dot(w)
    deff = h-y
    #每100次正反传播打印一次损失
    loss = deff.T.dot(deff)
    if i % 100 == 0:
        print(loss)
    #反向传播
    ddeff = 2 * deff
    dh = 1 * ddeff
    dw = X.T.dot(dh)
    w = w - lr * dw

[[ 70.]]
[[ 0.0078892]]
[[ 0.00078922]]
[[ 0.00011647]]
[[  2.53712989e-05]]
[[  6.73698338e-06]]
[[  1.91013569e-06]]
[[  5.51543066e-07]]
[[  1.60022359e-07]]
[[  4.64861570e-08]]


In [12]:
w

array([[ 0.99987689],
       [ 2.00015464],
       [ 2.99993077]])

In [13]:
X = np.array([[1,1,1],
              [0,1,1],
              [0,0,1]])


y = np.array([[6],
              [5],
              [3]])
w = np.zeros((3, 1))

In [14]:
lr = 0.01
for i in range(1000):
    dw = 2*X.T.dot(X.dot(w)-y)
    w = w - lr * dw

In [15]:
w

array([[ 0.99987689],
       [ 2.00015464],
       [ 2.99993077]])

In [16]:
w =  np.linalg.inv((X.T.dot(X))).dot(X.T).dot(y)

In [17]:
w

array([[ 1.],
       [ 2.],
       [ 3.]])

可以看到我们上述的三个方法都得到了$w1=1,w2=2,w3=3$的结果，而这个参数正好吻合了训练集